DROP TABLE IF EXISTS sap_structure;

CREATE TABLE sap_structure (
	Eintragsnummer INTEGER,
	AuftrArt VARCHAR,
	VerkOrg VARCHAR,
	VertrWeg VARCHAR,
	Sparte VARCHAR,
	Verkaufsbüro VARCHAR,
	"K=Kopf/P=Position" VARCHAR,
	KundenNr INTEGER,
	"Bestellnummer des Kunden" VARCHAR,
	BestellDatum VARCHAR,
	Wunschlieferdatum VARCHAR,
	Preisdatum VARCHAR,
	"Position" INTEGER,
	"MaterialNr." VARCHAR,
	Materialtext VARCHAR,
	"Betrag 2 Kommastellen" NUMERIC(6,2),
	"Menge Ganzahlg" INTEGER,
	Mengeneinheit VARCHAR,
	Auftragsnummer VARCHAR,
	Profitcenter VARCHAR,
	"Kopfnotiz Zeile 1 Kopf" VARCHAR,
	"Kopfnotiz Zeile 2 Kopf" VARCHAR,
	"Kopfnotiz Zeile 3 Kopf" VARCHAR,
	"Kopfnotiz Zeile 4 Kopf" VARCHAR,
	"Kopfnotiz Zeile 5 Kopf" VARCHAR,
	"Kopfnotiz Zeile 6 Kopf" VARCHAR,
	"Kopfnotiz Zeile 7 Kopf" VARCHAR,
	"Kopfnotiz Zeile 8 Kopf" VARCHAR,
	"Kopfnotiz Zeile 9 Kopf" VARCHAR,
	"Kopfnotiz Zeile 10 Kopf" VARCHAR,
	"Schlussnotiz Zeile 1 Kopf" VARCHAR,
	"Schlussnotiz Zeile 2 Kopf" VARCHAR,
	"Schlussnotiz Zeile 3 Kopf" VARCHAR,
	"Sachbearbeiter Zeile 1 Kopf" VARCHAR,
	"Sachbearbeiter Zeile 2 Kopf" VARCHAR,
	"Sachbearbeiter Zeile 3 Kopf" VARCHAR,
	"Sachbearbeiter Zeile 4 Kopf" VARCHAR,
	"Sachbearbeiter Zeile 5 Kopf" VARCHAR,
	"Kundenansprechperson Kopf" VARCHAR,
	"MaterialVerkaufstext Zeile 1 Position" VARCHAR,
	"MaterialVerkaufstext Zeile 2 Position" VARCHAR,
	"MaterialVerkaufstext Zeile 3 Position" VARCHAR,
	"MaterialVerkaufstext Zeile 4 Position" VARCHAR,
	"MaterialVerkaufstext Zeile 5 Position" VARCHAR,
	"PositionsNotiz Zeile 1 Position" VARCHAR,
	"PositionsNotiz Zeile 2 Position" VARCHAR,
	"PositionsNotiz Zeile 3 Position" VARCHAR,
	"PositionsNotiz Zeile 4 Position" VARCHAR,
	"PositionsNotiz Zeile 5 Position" VARCHAR,
	"Email Kunde" VARCHAR,
	"Name1 Debitor(Info)" VARCHAR,
	"Name2 Debitor(Info)" VARCHAR,
	"Strasse Debitor(Info)" VARCHAR,
	"PostLz(Info)" VARCHAR,
	"Ortschaft(Info)" VARCHAR,
	Zahlweg VARCHAR
)
;