COPY (
	SELECT
		Eintragsnummer,
		AuftrArt,
		VertrWeg,
		Sparte,
		"Verkaufsbüro",
		"K=Kopf/P=Position",
		KundenNr,
		"Bestellnummer des Kunden",
		BestellDatum,
		Wunschlieferdatum,
		Preisdatum,
		"Position",
		"MaterialNr.",
		Materialtext,
		"Betrag 2 Kommastellen",
		"Menge Ganzahlg",
		Mengeneinheit,
		Auftragsnummer,
		Profitcenter,
		"Kopfnotiz Zeile 1 Kopf",
		"Kopfnotiz Zeile 2 Kopf",
		"Kopfnotiz Zeile 3 Kopf",
		"Kopfnotiz Zeile 4 Kopf",
		"Kopfnotiz Zeile 5 Kopf",
		"Kopfnotiz Zeile 6 Kopf",
		"Kopfnotiz Zeile 7 Kopf",
		"Kopfnotiz Zeile 8 Kopf",
		"Kopfnotiz Zeile 9 Kopf",
		"Kopfnotiz Zeile 10 Kopf",
		"Schlussnotiz Zeile 1 Kopf",
		"Schlussnotiz Zeile 2 Kopf",
		"Schlussnotiz Zeile 3 Kopf",
		"Sachbearbeiter Zeile 1 Kopf",
		"Sachbearbeiter Zeile 2 Kopf",
		"Sachbearbeiter Zeile 3 Kopf",
		"Sachbearbeiter Zeile 4 Kopf",
		"Sachbearbeiter Zeile 5 Kopf",
		"Kundenansprechperson Kopf",
		"MaterialVerkaufstext Zeile 1 Position",
		"MaterialVerkaufstext Zeile 2 Position",
		"MaterialVerkaufstext Zeile 3 Position",
		"MaterialVerkaufstext Zeile 4 Position",
		"MaterialVerkaufstext Zeile 5 Position",
		"PositionsNotiz Zeile 1 Position",
		"PositionsNotiz Zeile 2 Position",
		"PositionsNotiz Zeile 3 Position",
		"PositionsNotiz Zeile 4 Position",
		"PositionsNotiz Zeile 5 Position",
		"Email Kunde",
		"Name1 Debitor(Info)",
		"Name2 Debitor(Info)",
		"Strasse Debitor(Info)",
		"PostLz(Info)",
		"Ortschaft(Info)",
		Zahlweg
	FROM
		afu_bootsanbindeplaetze.main.sap_structure)
TO ${csvPathSAP} WITH (HEADER, DELIMITER E'\t');