SELECT 
    nummer,
    bemerkung,
    geometrie,
    pikettdienst,
    pikettdienst_flugunfaelle,
    kommunikation_militaerjustiz
FROM 
    dsbjd_pikettregionen_militaerjustiz_v1.pikettregionen_pikettregion 
;