SELECT 
    CAST(NULLIF(EGID, '') AS int) AS EGID,
    CAST(NULLIF(EWID, '') AS int) AS EWID,
    CAST(NULLIF(EDID, '') AS int) AS EDID,
    NULLIF(WHGNR, '') AS WHGNR,
    NULLIF(WEINR, '') AS WEINR,
    CAST(NULLIF(WSTWK, '') AS int) AS WSTWK,
    NULLIF(WBEZ, '') AS WBEZ,
    CAST(NULLIF(WMEHRG, '') AS int) AS WMEHRG,
    CAST(NULLIF(WBAUJ, '') AS int) AS WBAUJ,
    CAST(NULLIF(WABBJ, '') AS int) AS WABBJ,
    CAST(NULLIF(WSTAT, '') AS int) AS WSTAT,
    CAST(NULLIF(WAREA, '') AS int) AS WAREA,
    CAST(NULLIF(WAZIM, '') AS int) AS WAZIM,
    CAST(NULLIF(WKCHE, '') AS int) AS WKCHE,
    NULLIF(WEXPDAT, '') AS WEXPDAT
FROM
    dwelling 
;