SELECT
    t_id,
    name_nummer,
    geometrie,
    funktion,
    kabelart,
    lagebestimmung,
    status,
    einbaujahr,
    ueberdeckung,
    zustand,
    eigentuemer,
    bemerkung,
    letzte_aenderung
FROM
    agi_leitungskataster_was.sia405_wasser_wi_kabel
;
