import ch.so.agi.gretl.tasks.*
import ch.so.agi.gretl.api.TransferSet
import de.undercouch.gradle.tasks.download.Download

apply plugin: 'ch.so.agi.gretl'

defaultTasks 'importXTF'

// ------------------------------------------------------------
// Directory Listing
// ------------------------------------------------------------

def xtfFolderPath = "${buildDir}/Downloads"
def unzipFolderPath = "${buildDir}/UnzipFolder"
def baseUrl = 'https://files.geo.so.ch/ch.so.agi.av.mopublic/hist/2024-01-01/'

def directoryListing = new URL(baseUrl).text
def zipFiles = directoryListing.findAll(/href="([^"]+\.zip)"/) { match, fileName ->
    fileName}

def duckDbPath = "${buildDir}/temp.duckdb"
def duckDbUri = "jdbc:duckdb:${duckDbPath}"
def duckDbFile = file(duckDbPath)

println "Gefundene ZIP-Dateien: ${zipFiles.size()}"


/// ------------------------------------------------------------
// DuckDB Schema einmalig erstellen
// ------------------------------------------------------------
tasks.register("createSchema", Ili2duckdbImportSchema) {
    dbfile = duckDbFile
    models = "SO_AGI_MOpublic_20190424"
    modeldir = file("$buildDir/ili").absolutePath +
               ";https://models.geo.admin.ch/"
    dbschema = "importschema_xtf"
}

// ------------------------------------------------------------
// Tasks pro Zip/XTF (Gemeinde)
// ------------------------------------------------------------
zipFiles.each { zipFileName ->
    // Dateiname ohne .zip
    def fileName = zipFileName.replaceFirst(/\.zip$/, '')
    // Eindeutiger Task-Name
    def taskSuffix = fileName.replaceAll('[^a-zA-Z0-9]', '_')
    // Dateien
    def zipFile = file("${xtfFolderPath}/${zipFileName}")
    def xtfFile = file("${unzipFolderPath}/${fileName}")

    // --------------------------------------------------------
    // Download Zip-Files
    // --------------------------------------------------------
    tasks.register("download_${taskSuffix}", Download) {
        description = "Download ${zipFileName}"
        src "${baseUrl}${zipFileName}"
        dest zipFile
        overwrite true
    }

    // --------------------------------------------------------
    // Zip-Files entpacken
    // --------------------------------------------------------
    tasks.register("unzip_${taskSuffix}", Copy) {
        description = "Unzip ${zipFileName}"
        dependsOn "download_${taskSuffix}"
        from zipTree(zipFile)
        into unzipFolderPath
    }

    // --------------------------------------------------------
    // DuckDB Import
    // --------------------------------------------------------
    tasks.register("import_${taskSuffix}", Ili2duckdbImport) {
        description = "Import ${fileName} into DuckDB"
        dependsOn "createSchema"
        dependsOn "unzip_${taskSuffix}"
        models = "SO_AGI_MOpublic_20190424"
        dbschema = "importschema_xtf"
        dataFile = files(xtfFile)
        dbfile = duckDbFile
        skipGeometryErrors = true
        disableAreaValidation = true
        disableValidation = true
    }
}

// ------------------------------------------------------------
// Gesamter Import
// ------------------------------------------------------------

tasks.register('importXTF') {
    dependsOn zipFiles.collect { zipFileName ->
        def fileName = zipFileName.replaceFirst(/\.zip$/, '')
        def taskSuffix = fileName.replaceAll('[^a-zA-Z0-9]', '_')
        "import_${taskSuffix}"
    }
}