import ch.so.agi.gretl.tasks.*
import ch.so.agi.gretl.api.TransferSet
import de.undercouch.gradle.tasks.download.Download

apply plugin: 'ch.so.agi.gretl'

defaultTasks 'createSchema_mopublic_hist'

// ------------------------------------------------------------
// Directory Listing
// ------------------------------------------------------------

def xtfFolderPath = "${buildDir}/Downloads"
def unzipFolderPath = "${buildDir}/UnzipFolder"
def baseUrl = 'https://files.geo.so.ch/ch.so.agi.av.mopublic/hist/2024-01-01/'

def directoryListing = new URL(baseUrl).text
def zipFiles = directoryListing.findAll(/href="([^"]+\.zip)"/) { match, fileName ->
    fileName}

def duckDbPath = "${buildDir}/temp.duckdb"
def duckDbUri = "jdbc:duckdb:${duckDbPath}"
def duckDbFile = file(duckDbPath)
def model_hist = "SO_AGI_MOpublic_20190424"

println "Gefundene ZIP-Dateien: ${zipFiles.size()}"


/// ------------------------------------------------------------
// DuckDB Schemas einmalig erstellen
// ------------------------------------------------------------
tasks.register("createSchema_objekte_historisch", Ili2duckdbImportSchema) {
    dbfile = duckDbFile
    models = "SO_AGI_Objekte_Historisch_Publikation_20260928"
    modeldir = file("$buildDir/ili").absolutePath +
               ";https://models.geo.admin.ch/"
    dbschema = "schema_objekte_historisch"
}

tasks.register("createSchema_mopublic_hist", Ili2duckdbImportSchema) {
    dependsOn "createSchema_objekte_historisch"
    dbfile = duckDbFile
    models = model_hist
    modeldir = file("$buildDir/ili").absolutePath +
               ";https://models.geo.admin.ch/"
    dbschema = "schema_mopublic_2024"
}

// ------------------------------------------------------------
// Tasks pro Zip/XTF (Gemeinde)
// ------------------------------------------------------------
zipFiles.each { zipFileName ->
    // Dateiname ohne .zip
    def fileName = zipFileName.replaceFirst(/\.zip$/, '')
    // Eindeutiger Task-Name
    def taskSuffix = fileName.replaceAll('[^a-zA-Z0-9]', '_')
    // Dateien
    def zipFile = file("${xtfFolderPath}/${zipFileName}")
    def xtfFile = file("${unzipFolderPath}/${fileName}")

    // --------------------------------------------------------
    // Download Zip-Files
    // --------------------------------------------------------
    tasks.register("download_${taskSuffix}", Download) {
        description = "Download ${zipFileName}"
        src "${baseUrl}${zipFileName}"
        dest zipFile
        overwrite true
    }

    // --------------------------------------------------------
    // Zip-Files entpacken
    // --------------------------------------------------------
    tasks.register("unzip_${taskSuffix}", Copy) {
        description = "Unzip ${zipFileName}"
        dependsOn "download_${taskSuffix}"
        from zipTree(zipFile)
        into unzipFolderPath
    }

    // --------------------------------------------------------
    // DuckDB Import
    // --------------------------------------------------------
    tasks.register("import_${taskSuffix}", Ili2duckdbImport) {
        description = "Import ${fileName} into DuckDB"
        dependsOn "createSchema_mopublic_HIST"
        dependsOn "unzip_${taskSuffix}"
        models = model_hist
        dbschema = "schema_mopublic_2024"
        dataFile = files(xtfFile)
        dbfile = duckDbFile
        skipGeometryErrors = true
        disableAreaValidation = true
        disableValidation = true
    }
}

// ------------------------------------------------------------
// Gesamter Import
// ------------------------------------------------------------

tasks.register('importXTF') {
    dependsOn zipFiles.collect { zipFileName ->
        def fileName = zipFileName.replaceFirst(/\.zip$/, '')
        def taskSuffix = fileName.replaceAll('[^a-zA-Z0-9]', '_')
        "import_${taskSuffix}"
    }
}

tasks.register("copy_data",SqlExecutor){
    dependsOn "importXTF"
    database = [dbUriDuckDB]
    sqlFiles = files(
        'load_extension_spatial.sql',
        'load_extension_postgres.sql',
        'agi_objekte_hist_bodenbedeckung.sql',
        'agi_objekte_hist_einzelobjekt.sql'
    )
}

tasks.register('transferData', Db2Db) {
    sourceDb = [dbUriDuckDB]
    targetDb = [dbUriPub, dbUserPub, dbPwdPub]
    transferSets = [
        new TransferSet('afu_kleinklaeranlagen_pub.sql', 'afu_klaeranlagen_pub_v1.klaeranlagen_kleinklaeranlage', true),
        new TransferSet('afu_ara_pub.sql', 'afu_klaeranlagen_pub_v1.klaeranlagen_ara', true)

    ];
}