SELECT
	/*
	t_basket,
	t_datasetname,
	*/
	wfn.egrid,
	wfbp.flaeche AS waldflaeche, --nur als Kontrolle, am Schluss löschen
	
	--- Waldfunktionsflächen ---
	SUM(wfn.flaeche) FILTER (WHERE funktion = 'Wirtschaftswald') AS wirtschaftswald,
	SUM(wfn.flaeche) FILTER (WHERE funktion = 'Schutzwald') AS schutzwald,
	SUM(wfn.flaeche) FILTER (WHERE funktion = 'Erholungswald	') AS erholungswald,
	SUM(wfn.flaeche) FILTER (WHERE funktion = 'Biodiversitaet') AS biodiversitaet,
	SUM(wfn.flaeche) FILTER (WHERE funktion = 'Schutzwald_Biodiversitaet') AS schutzwald_biodiversitaet,
	
	--- Waldnutzungsflächen ---
	SUM(wfn.flaeche) FILTER (WHERE nutzungskategorie = 'Wald_bestockt') AS wald_bestockt,
	SUM(wfn.flaeche) FILTER (WHERE nutzungskategorie = 'Nachteilige_Nutzung') AS nachteilige_nutzung,
	SUM(wfn.flaeche) FILTER (WHERE nutzungskategorie = 'Waldstrasse') AS waldstrasse,
	SUM(wfn.flaeche) FILTER (WHERE nutzungskategorie = 'Maschinenweg') AS maschinenweg,
	SUM(wfn.flaeche) FILTER (WHERE nutzungskategorie = 'Bauten_Anlagen') AS bauten_anlagen,
	SUM(wfn.flaeche) FILTER (WHERE nutzungskategorie = 'Rodungsflaechen_temporaer') AS rodung_temporaer,
	SUM(wfn.flaeche) FILTER (WHERE nutzungskategorie = 'Gewaesser') AS gewaesser,
	
	--- Biodiversitätsobjekt --
	SUM(wfn.flaeche) FILTER (WHERE biodiversitaet_objekt = 'Waldreservat') AS waldreservat,
	SUM(wfn.flaeche) FILTER (WHERE biodiversitaet_objekt = 'Altholzinsel') AS altholzinsel,
	SUM(wfn.flaeche) FILTER (WHERE biodiversitaet_objekt = 'Waldrand') AS waldrand,
	SUM(wfn.flaeche) FILTER (WHERE biodiversitaet_objekt = 'Lichter_Wald') AS lichter_wald,
	SUM(wfn.flaeche) FILTER (WHERE biodiversitaet_objekt = 'Lebensraum_prioritaer') AS lebensraum_prioritaer,
	SUM(wfn.flaeche) FILTER (WHERE biodiversitaet_objekt = 'Andere_Foerderflaeche') AS andere_foerderflaeche
	
	/*
	waldreservat,
	altholzinsel,
	waldrand,
	lichter_wald,
	lebensraum_prioritaer,
	andere_foerderflaeche,
	waldflaeche_produktiv,
	waldflaeche_unproduktiv,
	wirtschaftswald_produktiv,
	wirtschaftswald_unproduktiv,
	schutzwald_produktiv,
	schutzwald_unproduktiv,
	erholungswald_produktiv,
	erholungswald_unproduktiv,
	biodiversitaet_produktiv,
	biodiversitaet_unproduktiv,
	schutzwald_bio_produktiv,
	schutzwald_bio_unproduktiv,
	waldflaeche_hiebrel,
	waldflaeche_n_hiebrel,
	wirtschaftswald_hiebrel,
	wirtschaftswald_n_hiebrel,
	schutzwald_hiebrel,
	schutzwald_n_hiebrel,
	erholungswald_hiebrel,
	erholungswald_n_hiebrel,
	biodiversitaet_hiebrel,
	biodiversitaet_n_hiebrel,
	schutzwald_bio_hiebrel,
	schutzwald_bio_n_hiebrel,
	wald_bestockt_hiebrel,
	wald_bestockt_n_hiebrel,
	nachteilige_nutzung_hiebrel,
	nachteilige_nutzung_n_hiebrel,
	wirtschaftswald_wald_bestockt,
	wirtschaftswald_nt_nutzung,
	wirtschaftswald_waldstrasse,
	wirtschaftswald_maschinenweg,
	wirtschaftswald_bauanl,
	wirtschaftswald_gewaesser,
	wirtschaftswald_rodung_temp,
	schutzwald_wald_bestockt,
	schutzwald_nt_nutzung,
	schutzwald_waldstrasse,
	schutzwald_maschinenweg,
	schutzwald_bauanl,
	schutzwald_gewaesser,
	schutzwald_rodung_temp,
	erholungswald_wald_bestockt,
	erholungswald_nt_nutzung,
	erholungswald_waldstrasse,
	erholungswald_maschinenweg,
	erholungswald_bauanl,
	erholungswald_gewaesser,
	erholungswald_rodung_temp,
	biodiversitaet_wald_bestockt,
	biodiversitaet_nt_nutzung,
	biodiversitaet_waldstrasse,
	biodiversitaet_maschinenweg,
	biodiversitaet_bauanl,
	biodiversitaet_gewaesser,
	biodiversitaet_rodung_temp,
	schutzwald_bio_wald_bestockt,
	schutzwald_bio_nt_nutzung,
	schutzwald_bio_waldstrasse,
	schutzwald_bio_maschinenweg,
	schutzwald_bio_bauanl,
	schutzwald_bio_gewaesser,
	schutzwald_bio_rodung_temp,
	gemeinde,
	grundbuch,
	forstkreis,
	forstkreis_txt,
	forstrevier,
	forstbetrieb,
	wirtschaftszone,
	wirtschaftszone_txt,
	grundstuecknummer,
	flaechenmass,
	eigentuemer,
	eigentuemer_txt,
	eigentuemerinformation,
	wytweide_flaeche,
	waldflaeche,
	geometrie,
	bemerkung
	*/
FROM 
	waldfunktion_waldnutzung_flaechen_berechnet AS wfn
LEFT JOIN waldflaechen_berechnet_plausibilisiert AS wfbp
	ON wfn.egrid = wfbp.egrid
GROUP BY 
	wfn.egrid,
	wfbp.flaeche
ORDER BY
	wfbp.flaeche DESC