SELECT 
  t_id, 
  t_ili_tid, 
  geometrie, 
  letalitaetsradius_art, 
  letalitaetsradius, 
  bevoelkerung_typ, 
  bevoelkerung_anzahl, 
  risikozahl, 
  anzahl_tote, 
  id_szenario 
FROM 
  ${DB_Schema_QRcat}.qrcat_letalflaeche;
