SELECT 
    typ, 
    typ_txt, 
    nbident, 
    nummer, 
    hoehe, 
    bfs_nr, 
    lagegenauigkeit, 
    hoehengenauigkeit, 
    punktzeichen, 
    punktzeichen_txt, 
    orientierung, 
    hali, 
    vali, 
    importdatum, 
    nachfuehrung, 
    geometrie, 
    pos
FROM 
    agi_mopublic_pub.mopublic_fixpunkt
;
