SELECT 
    strassenname, 
    hausnummer, 
    egid, 
    edid, 
    plz, 
    ortschaft, 
    status, 
    ist_offizielle_bezeichnung, 
    hoehenlage, 
    gebaeudename, 
    bfs_nr, 
    orientierung, 
    hali, 
    vali, 
    importdatum, 
    nachfuehrung, 
    lage, 
    pos
FROM 
    agi_mopublic_pub.mopublic_gebaeudeadresse
;
