pipeline {
    agent none
    options {
        timeout(time: 7, unit: 'DAYS')
    }
    stages {
        stage('Kästchen in Jenkins') {
            agent {
                kubernetes {
                    inheritFrom env.NODE_LABEL ?: 'gretl'
                    yamlMergeStrategy merge()
                    yaml """
                    spec:
                      containers:
                        - name: gretl
                          volumeMounts:
                            - name: datahub-workdir-volume
                              mountPath: /work
                              subPath: datahub
                      volumes:
                        - name: datahub-workdir-volume
                          persistentVolumeClaim:
                            claimName: ${env.OPENSHIFT_PROJECT_NAME}-lowback
"""
                }
            }
            steps {
                script { currentBuild.description = "${params.buildDescription}" }
                git url: "${env.GIT_REPO_URL}", branch: "${params.BRANCH ?: 'main'}", changelog: false
                container('gretl') {
                    dir(env.JOB_BASE_NAME) {
                        sh "gretl fubar"
                    }
                }
            }
        }
    }
    /*
    post {
        success {
            emailext (
                recipientProviders: [requestor()],
                subject: "Daten der Nutzungsplanung für BFS-Nr. ${params.bfsnr} sind publiziert (GRETL-Job ${JOB_NAME} ${BUILD_DISPLAY_NAME})",
                body: "Die Daten der Nutzungsplanung für BFS-Nr. ${params.bfsnr} des GRETL-Jobs ${JOB_NAME} (${BUILD_DISPLAY_NAME}) wurden erfolgreich publiziert. Die Log-Meldungen dazu finden Sie unter ${RUN_DISPLAY_URL}."
            )
        }
        unsuccessful {
            emailext (
                to: "${currentBuild.getBuildCauses()[0]._class == 'hudson.model.Cause$UserIdCause' ? emailextrecipients([requestor()]) : '$DEFAULT_RECIPIENTS'}",
                subject: "GRETL-Job ${JOB_NAME} (${BUILD_DISPLAY_NAME}) ist fehlgeschlagen",
                body: "Die Ausführung des GRETL-Jobs ${JOB_NAME} (${BUILD_DISPLAY_NAME}) war nicht erfolgreich. Details dazu finden Sie in den Log-Meldungen unter ${RUN_DISPLAY_URL}."
            )
        }
    }
    */
}