version: '3'
services:
  processing-db:
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_DB: processing
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "54324:5432"
    volumes:
      - sshd_processing:/sshd
      - pgconf_processing:/pgconf
      - pgdata_processing:/pgdata
      - pgwal_processing:/pgwal
      - recover_processing:/recover
      - backrestrepo_processing:/backrestrepo
    hostname: primary-processing
volumes:
  sshd_processing:
  pgconf_processing:
  pgdata_processing:
  pgwal_processing:
  recover_processing:
  backrestrepo_processing:
