pipeline {
    agent {
        kubernetes {
            inheritFrom env.NODE_LABEL ?: 'gretl'
            yamlMergeStrategy merge()
            yaml '''
            spec:
              containers:
                - name: processing-db
                  image: sogis/postgis:16-3.4-bookworm
                  resources:
                    requests:
                      cpu: 600m
                      memory: "4Gi"
                    limits:
                      cpu: "2"
                      memory: "8Gi"
                  env:
                    - name: POSTGRES_USER
                      value: processing
                    - name: POSTGRES_PASSWORD
                      value: processing
                    - name: PGDATA
                      value: /var/lib/postgresql/data/pgdata
                  volumeMounts:
                    - name: postgresql-data-volume
                      mountPath: /var/lib/postgresql/data
              volumes:
                - name: postgresql-data-volume
                  emptyDir: {}
'''
        }
    }
    options {
        timeout(time: 6, unit: 'HOURS')
    }
    stages {
        stage('Run GRETL job') {
            environment {
                ORG_GRADLE_PROJECT_dbUriProcessing = 'jdbc:postgresql://127.0.0.1/processing'
                ORG_GRADLE_PROJECT_dbUserProcessing = 'processing'
                ORG_GRADLE_PROJECT_dbPwdProcessing = 'processing'
            }
            steps {
                git url: "${env.GIT_REPO_URL}", branch: "${params.BRANCH ?: 'main'}", changelog: false
                container('gretl') {
                    dir(env.JOB_BASE_NAME) {
                        sh 'gretl'
                    }
                }
            }
        }
    }
    post {
        unsuccessful {
            emailext (
                // If build was started by a user ("UserIdCause"), then set to user that started the build (the "requestor");
                // otherweise set to $DEFAULT_RECIPIENTS
                // Good to know: $DEFAULT_RECIPIENTS is not a variable,
                // but rather a token which will be replaced by the Email Extension plugin
                // Docs: https://plugins.jenkins.io/email-ext/#plugin-content-tokens
                to: "${currentBuild.getBuildCauses()[0]._class == 'hudson.model.Cause$UserIdCause' ? emailextrecipients([requestor()]) : '$DEFAULT_RECIPIENTS'}",
                subject: "GRETL-Job ${JOB_NAME} (${BUILD_DISPLAY_NAME}) ist fehlgeschlagen",
                body: "Die Ausführung des GRETL-Jobs ${JOB_NAME} (${BUILD_DISPLAY_NAME}) war nicht erfolgreich. Details dazu finden Sie in den Log-Meldungen unter ${RUN_DISPLAY_URL}."
            )
        }
    }
}
