logRotator.numToKeep=unlimited
parameters.stringParams=bfsnr;;BFS-Nr. der Gemeinde welche publiziert werden soll.@\
                        buildDescription;Keine Beschreibung angegeben;Beschreibung/Grund für die Publikation der Daten
authorization.permissions=GA_Gretl_bjsvw,GA_Gretl_barpa
