DELETE FROM arp_waldabstandslinien_mgdm_v1.geobasisdaten_typ_dokument
;
DELETE FROM arp_waldabstandslinien_mgdm_v1.geobasisdaten_waldabstand_linie
;
DELETE FROM arp_waldabstandslinien_mgdm_v1.geobasisdaten_typ
;
DELETE FROM arp_waldabstandslinien_mgdm_v1.localiseduri
;
DELETE FROM arp_waldabstandslinien_mgdm_v1.multilingualuri
;
DELETE FROM arp_waldabstandslinien_mgdm_v1.rechtsvorschrften_dokument
;
DELETE FROM arp_waldabstandslinien_mgdm_v1.t_ili2db_basket 
;
DELETE FROM arp_waldabstandslinien_mgdm_v1.t_ili2db_dataset 
;
