SELECT 
	t_id,
	t_basket,
	t_datasetname,
	t_ili_tid,
	funktion,
	biodiversitaet_id,
	biodiversitaet_objekt,
	wytweide,
	geometrie,
	bemerkung,
	schutzwald_r,
	t_lastchange,
	t_createdate,
	t_user
FROM 
	awjf_waldplan_v2.waldplan_waldfunktion