DELETE FROM awjf_statische_waldgrenze_mgdm_v1.geobasisdaten_typ_dokument
;
DELETE FROM awjf_statische_waldgrenze_mgdm_v1.geobasisdaten_waldgrenze_linie 
;
DELETE FROM awjf_statische_waldgrenze_mgdm_v1.geobasisdaten_typ
;
DELETE FROM awjf_statische_waldgrenze_mgdm_v1.localiseduri
;
DELETE FROM awjf_statische_waldgrenze_mgdm_v1.multilingualuri
;
DELETE FROM awjf_statische_waldgrenze_mgdm_v1.geobasisdaten_geometrie_dokument
;
DELETE FROM awjf_statische_waldgrenze_mgdm_v1.rechtsvorschrften_dokument
;
