DELETE FROM awjf_statische_waldgrenzen_mgdm.geobasisdaten_typ_dokument
;
DELETE FROM awjf_statische_waldgrenzen_mgdm.geobasisdaten_waldgrenze_linie 
;
DELETE FROM awjf_statische_waldgrenzen_mgdm.geobasisdaten_typ
;
DELETE FROM awjf_statische_waldgrenzen_mgdm.localiseduri
;
DELETE FROM awjf_statische_waldgrenzen_mgdm.multilingualuri
;
DELETE FROM awjf_statische_waldgrenzen_mgdm.rechtsvorschrften_hinweiseweiteredokumente
;
DELETE FROM awjf_statische_waldgrenzen_mgdm.rechtsvorschrften_dokument
;
