SELECT
    ogc_fid,
    tid,
    nbident,
    identifikator,
    beschreibung,
    perimeter,
    gueltigkeit,
    gueltigkeit_txt,
    gueltigereintrag,
    gbeintrag,
    datum1,
    datum2,
    gem_bfs,
    los,
    lieferdatum
FROM
    av_avdpool_ng.liegenschaften_lsnachfuehrung
;
