SELECT
    ogc_fid,
    tid,
    liegenschaft_von,
    nummerteilgrundstueck,
    geometrie,
    flaechenmass,
    gem_bfs,
    los,
    lieferdatum
FROM
    av_avdpool_ng.liegenschaften_liegenschaft
;
