INSERT INTO
    awjf_programm_biodiversitaet_wald_v1.biodiversitt_wald_biotopbaum
    (
        baum_id,
        baumkategorie,
        inventur_jahr,
        wirtschaftszone,
        gesuchsnummer,
        waldeigentuemer_code,
        baumart,
        bhd,
        baumhoehe,
        betriebsart,
        merkmal_1,
        beschreibung_merkmal_1,
        merkmal_2,
        beschreibung_merkmal_2,
        merkmal_3,
        beschreibung_merkmal_3,
        massnahmen,
        besonderheiten,
        bemerkungen,
        tp_inventar,
        auszahlung_beitrag,
        auszahlung_beitrag_jahr,
        geometrie
    )
    SELECT
        baum_id,
        baumkategorie,
        inventur_jahr,
        wirtschaftszone,
        gesuchsnummer,
        waldeigentuemer_code,
        baumart,
        bhd,
        baumhoehe,
        betriebsart,
        merkmal_1,
        beschreibung_merkmal_1,
        merkmal_2,
        beschreibung_merkmal_2,
        merkmal_3,
        beschreibung_merkmal_3,
        massnahmen,
        besonderheiten,
        bemerkungen,
        tp_inventar,
        auszahlung_beitrag,
        auszahlung_beitrag_jahr,
        (SELECT ST_SetSRID(ST_Point(x_koordinate, y_koordinate), 2056)) AS geometrie
    FROM
        awjf_programm_biodiversitaet_wald_v1.biodiversitt_wald_biotopbaum_import
;
