BEGIN;

DELETE FROM awjf_holznutzungsbewilligung_staging_v1.localisedtext;
DELETE FROM awjf_holznutzungsbewilligung_staging_v1.multilingualtext;
DELETE FROM awjf_holznutzungsbewilligung_staging_v1.holznutzung_mengeholzart;
DELETE FROM awjf_holznutzungsbewilligung_staging_v1.holznutzung_holznutzungsbewilligung_egrid;
DELETE FROM awjf_holznutzungsbewilligung_staging_v1.holznutzung_holznutzungsbewilligung_gemeinde;
DELETE FROM awjf_holznutzungsbewilligung_staging_v1.holznutzung_holznutzungsbewilligung_revier;
DELETE FROM awjf_holznutzungsbewilligung_staging_v1.holznutzung_holznutzungsbewilligung;
DELETE FROM awjf_holznutzungsbewilligung_staging_v1.codelisten_bewilligte_holzart_catalogue;
DELETE FROM awjf_holznutzungsbewilligung_staging_v1.t_ili2db_basket;
DELETE FROM awjf_holznutzungsbewilligung_staging_v1.t_ili2db_dataset;

COMMIT;