DELETE FROM arp_laermempfindlichkeitsstufen_mgdm.geobasisdaten_typ_dokument
;
DELETE FROM arp_laermempfindlichkeitsstufen_mgdm.geobasisdaten_laermempfindlichkeit_zonenflaeche
;
DELETE FROM arp_laermempfindlichkeitsstufen_mgdm.geobasisdaten_typ
;
DELETE FROM arp_laermempfindlichkeitsstufen_mgdm.localiseduri
;
DELETE FROM arp_laermempfindlichkeitsstufen_mgdm.multilingualuri
;
DELETE FROM arp_laermempfindlichkeitsstufen_mgdm.rechtsvorschrften_hinweisweiteredokumente
;
DELETE FROM arp_laermempfindlichkeitsstufen_mgdm.rechtsvorschrften_dokument
;
