DELETE FROM arp_waldabstandslinien_mgdm.geobasisdaten_typ_dokument
;
DELETE FROM arp_waldabstandslinien_mgdm.geobasisdaten_waldabstand_linie 
;
DELETE FROM arp_waldabstandslinien_mgdm.geobasisdaten_typ
;
DELETE FROM arp_waldabstandslinien_mgdm.localiseduri
;
DELETE FROM arp_waldabstandslinien_mgdm.multilingualuri
;
DELETE FROM arp_waldabstandslinien_mgdm.rechtsvorschrften_hinweiseweiteredokumente
;
DELETE FROM arp_waldabstandslinien_mgdm.rechtsvorschrften_dokument
;
