SELECT 
    gesamt.emiss_so2 AS so2_gesamt, 
    gesamt.emiss_nox AS nox_gesamt, 
    gesamt.emiss_co AS co_gesamt, 
    gesamt.emiss_ch4 AS ch4_gesamt, 
    gesamt.emiss_pm10 AS pm10_gesamt, 
    gesamt.emiss_nh3 AS nh3_gesamt, 
    gesamt.emiss_nmvoc AS nmvoc_gesamt, 
    gesamt.emiss_co2 AS co2_gesamt, 
    gesamt.emiss_n2o AS n2o_gesamt, 
    gesamt.emiss_xkw AS xkw_gesamt, 
    haushalte.emiss_so2 AS so2_haushalte, 
    haushalte.emiss_nox AS nox_haushalte, 
    haushalte.emiss_co AS co_haushalte, 
    haushalte.emiss_ch4 AS ch4_haushalte, 
    haushalte.emiss_pm10 AS pm10_haushalte, 
    haushalte.emiss_nh3 AS nh3_haushalte, 
    haushalte.emiss_nmvoc AS nmvoc_haushalte, 
    haushalte.emiss_co2 AS co2_haushalte, 
    haushalte.emiss_n2o AS n2o_haushalte, 
    haushalte.emiss_xkw AS xkw_haushalte, 
    biogen.emiss_so2 AS so2_biogen, 
    biogen.emiss_nox AS nox_biogen, 
    biogen.emiss_co AS co_biogen, 
    biogen.emiss_ch4 AS ch4_biogen, 
    biogen.emiss_pm10 AS pm10_biogen, 
    biogen.emiss_nh3 AS nh3_biogen, 
    biogen.emiss_nmvoc AS nmvoc_biogen, 
    biogen.emiss_co2 AS co2_biogen, 
    biogen.emiss_n2o AS n2o_biogen, 
    biogen.emiss_xkw AS xkw_biogen,
    industrie_und_gewerbe.emiss_so2 AS so2_industrie_und_gewerbe, 
    industrie_und_gewerbe.emiss_nox AS nox_industrie_und_gewerbe, 
    industrie_und_gewerbe.emiss_co AS co_industrie_und_gewerbe, 
    industrie_und_gewerbe.emiss_ch4 AS ch4_industrie_und_gewerbe, 
    industrie_und_gewerbe.emiss_pm10 AS pm10_industrie_und_gewerbe, 
    industrie_und_gewerbe.emiss_nh3 AS nh3_industrie_und_gewerbe, 
    industrie_und_gewerbe.emiss_nmvoc AS nmvoc_industrie_und_gewerbe, 
    industrie_und_gewerbe.emiss_co2 AS co2_industrie_und_gewerbe, 
    industrie_und_gewerbe.emiss_n2o AS n2o_industrie_und_gewerbe, 
    industrie_und_gewerbe.emiss_xkw AS xkw_industrie_und_gewerbe, 
    land_und_forstwirtschaft.emiss_so2 AS so2_land_und_forstwirtschaft, 
    land_und_forstwirtschaft.emiss_nox AS nox_land_und_forstwirtschaft, 
    land_und_forstwirtschaft.emiss_co AS co_land_und_forstwirtschaft, 
    land_und_forstwirtschaft.emiss_ch4 AS ch4_land_und_forstwirtschaft, 
    land_und_forstwirtschaft.emiss_pm10 AS pm10_land_und_forstwirtschaft, 
    land_und_forstwirtschaft.emiss_nh3 AS nh3_land_und_forstwirtschaft, 
    land_und_forstwirtschaft.emiss_nmvoc AS nmvoc_land_und_forstwirtschaft, 
    land_und_forstwirtschaft.emiss_co2 AS co2_land_und_forstwirtschaft, 
    land_und_forstwirtschaft.emiss_n2o AS n2o_land_und_forstwirtschaft, 
    land_und_forstwirtschaft.emiss_xkw AS xkw_land_und_forstwirtschaft, 
    verkehr.emiss_so2 AS so2_verkehr, 
    verkehr.emiss_nox AS nox_verkehr, 
    verkehr.emiss_co AS co_verkehr, 
    verkehr.emiss_ch4 AS ch4_verkehr, 
    verkehr.emiss_pm10 AS pm10_verkehr, 
    verkehr.emiss_nh3 AS nh3_verkehr, 
    verkehr.emiss_nmvoc AS nmvoc_verkehr, 
    verkehr.emiss_co2 AS co2_verkehr, 
    verkehr.emiss_n2o AS n2o_verkehr, 
    COALESCE(verkehr.emiss_xkw,0) AS xkw_verkehr, 
    ST_GeometryN(gesamt.wkb_geometry,generate_series(1, ST_NumGeometries(gesamt.wkb_geometry))) AS geometrie 
FROM 
    ekat2015.gesamt_mapserver gesamt, 
    ekat2015.haushalte_mapserver haushalte, 
    ekat2015.biogene_quellen_mapserver biogen, 
    ekat2015.ind_gewerbe_mapserver industrie_und_gewerbe, 
    ekat2015.land_forst_mapserver land_und_forstwirtschaft, 
    ekat2015.verkehr_mapserver verkehr
WHERE 
    gesamt.xkoord = haushalte.xkoord AND gesamt.ykoord = haushalte.ykoord
    AND 
    gesamt.xkoord = biogen.xkoord AND gesamt.ykoord = biogen.ykoord 
    AND
    gesamt.xkoord = industrie_und_gewerbe.xkoord AND gesamt.ykoord = industrie_und_gewerbe.ykoord
    AND 
    gesamt.xkoord = land_und_forstwirtschaft.xkoord AND gesamt.ykoord = land_und_forstwirtschaft.ykoord
    AND 
    gesamt.xkoord = verkehr.xkoord AND gesamt.ykoord = verkehr.ykoord;
