logRotator.numToKeep=30
parameters.stashedFile=uploadFile
parameters.stringParams=ili2pgDataset;;Name des Ziel-Dataset angeben (Bsp: 2022_Himmelried)
authorization.permissions=GA_Gretl_bdafu,GA_Gretl_vkfaa
