logRotator.numToKeep=30
authorization.permissions=GA_Gretl_bdafu,GA_Gretl_vkfaa,bjsvwsch
parameters.stringParams=auftragskennung;;Auftragskennung, welche freigegeben und dem "main-Dataset" hinzugefügt werden soll.
nodeLabel=gretl-3.2
