select 
    pid_gelan as pid_15, 
    bfs_nummer_wohnsitz as gid,
    coalesce(gemeinde_wohnsitz,'') as gid_name,
    coalesce(name_vorname,'') as name_vorname,
    coalesce(aname,'') as name, 
    coalesce(name_trennzeichen,'') as name_trenner, 
    coalesce(zweitname,'') as zweitname,
    coalesce(vorname,'') as vorname,
    coalesce(adresse_strasse,'') as adresse,
    coalesce(adresse_hausnummer,'') as adr_nr,
    coalesce(postfachnummer,'') as pf_nr,
    coalesce(plz,'') as plz,
    coalesce(ortschaft,'') as ort,
    coalesce(anrede,'') as anrede,
    coalesce(briefanrede,'') as briefanr,
    coalesce(sprache,'') as sprache,
    coalesce(telefon_privat,'') as tel_p,
    coalesce(telefon_geschaeft,'') as tel_g,
    coalesce(telefon_mobil,'') as mobile,
    coalesce(mailadresse,'') as email,
    geburtsdatum as geb_datum,
    enddatum as ende_dat,
    coalesce(sozialversicherungsnummer,'') as nvn, 
    coalesce(personen_typ,'') as pers_typ,
    coalesce(rechtsform,'') as rechtsform,
    coalesce(typ_zahlverbindung,'') as typ_zahlverbindung,
    coalesce(bank,'') as bank,
    clearing as clearing,
    coalesce(bankkonto,'') as bkto,
    coalesce(postkonto,'') as pckto,
    coalesce(iban,'') as iban,
    coalesce(prueftext_iban,'') as text_iban,
    pid_beguenstigter as pid_beguenstigter,
    coalesce(beguenstigter,'') as beguenstigter
from 
    alw_landwirtschaft_tierhaltung_v1.betrbsdttrktrdten_gelan_person bgp 
