SELECT 
    jaehrlichkeit, 
    fliessgeschwindigkeit, 
    prozessquelle, 
    bemerkung, 
    geometrie, 
    datenherkunft, 
    auftrag_neudaten
FROM 
    afu_naturgefahren_staging_v1.kennwert_ueberschwemmung_geschwindigkeit
;