import ch.so.agi.gretl.tasks.*
import ch.so.agi.gretl.api.TransferSet

apply plugin: 'ch.so.agi.gretl'

defaultTasks 'csvImport'

def csvFile = file("${buildDir}/in/uploadFile.csv")

/*
tasks.register('validateCSVFile', CsvValidator) {
    models = "SO_AFU_Klaeranlagen_20260708"
    firstLineIsHeader = true
    dataFiles = [file("build/in/uploadFile.csv")]
    valueSeparator = ';'
}
*/

tasks.register('deleteData', SqlExecutor) {
    dependsOn "validateCSVFile"
    description = 'Bisherige Daten löschen'
    database = [dbUriEdit, dbUserEdit, dbPwdEdit]
    sqlFiles = files("delete_csv.sql")
}

// Import CSV-Datei
tasks.register('csvImport',  CsvImport) {
    dependsOn "deleteData"
    database = [dbUriEdit, dbUserEdit, dbPwdEdit]
    schemaName = "afu_klaeranlagen_v1"
    tableName = "klaeranlagen_kleinklaeranlage_import"
    firstLineIsHeader = true
    valueSeparator = ';'
    dataFile = csvFile
}
