import ch.so.agi.gretl.tasks.*
import ch.so.agi.gretl.api.TransferSet

apply plugin: 'ch.so.agi.gretl'

defaultTasks 'importXTF'

def zipFile = file("${buildDir}/in/uploadFile.zip")
def xtfFile = files("${buildDir}/in/uploadFile.xtf")

// Da die XTF-Datei für den Uplaod zu gross ist, muss sie erst in eine Zip-Datei gepackt werden. //
tasks.register("unzipFile", Copy) {
    description = "Unzip Upload-File"
    from zipTree(zipFile)
    into "${buildDir}/in/"
}

tasks.register('importXTF', Ili2pgImport) {
    description = "Import unzipped XTF-File into database"
    dependsOn "unzipFile"
    database = [dbUriPub, dbUserPub, dbPwdPub]
    dbschema = 'avt_strassenlaermflaechen_pub_v1'
    models = 'SO_AVT_Strassenlaermflaechen_Publikation_20260421'
    disableValidation = false
    deleteData = true
    dataFile = xtfFile
}