logRotator.numToKeep=30
authorization.permissions=gretl-users-bdafu
nodeLabel=gretl-3.2
parameters.stashedFile=xyz.zip
parameters.stringParams=anlage_id;;ID der Anlage, deren Schiesslärmdaten importiert werden sollen. Beispiel für die ID: 80.2