DELETE FROM afu_ewsabfrage_2d_staging_v2.abfrageperimeter;
DELETE FROM afu_ewsabfrage_2d_staging_v2.abklaerung;
DELETE FROM afu_ewsabfrage_2d_staging_v2.grundstueck;
DELETE FROM afu_ewsabfrage_2d_staging_v2.hinweis;
DELETE FROM afu_ewsabfrage_2d_staging_v2.tiefenbeschraenkung;
