logRotator.numToKeep=2
parameters.stringParams=dbname;edit;Name der Datenbank, aus der exportiert wird (edit oder pub)@\
                        schemanames;mySchema1 mySchema2 ...;Name der Schemas, die exportiert werden sollen (mit Leerschlag getrennt)
