SELECT
    streckentyp,
    passagieranzahl_pro_werktag_2015,
    passagieranzahl_in_abendspitzen_2015,
    passagieranzahl_pro_werktag_2040,
    passagieranzahl_in_abendspitzen_2040,
    geometrie
FROM
    avt_gesamtverkehrsmodell_2015_v1.oev_passagiere
;
