SELECT
    t_id,
    t_ili_tid,
    bfs_nummer,
    hoheitsgebietsname,
    hoheitsgebietsart,
    bezirk,
    kanton,
    land,
    datum_aenderung,
    geometrie
FROM
    agi_swissboundaries3d_pub.swissboundaries3d_hoheitsgebiet
;