SELECT
    ogc_fid AS t_id,
    geometrie,
    av_lieferdatum,
    av_gem_bfs,
    av_nbident,
    av_nummer,
    av_art,
    av_art_txt,
    av_flaeche,
    av_mutation_id,
    av_mut_beschreibung,
    kaso_gemeinde,
    kaso_bfs_nr,
    kaso_nbident,
    kaso_gb_nr,
    kaso_art,
    kaso_flaeche,
    flaechen_differenz,
    fehlerart
FROM
    av_kaso_abgleich.differenzen
;