SELECT
    ogc_fid AS t_id,
    tid,
    strassenstueck_von,
    geometrie,
    anfangspunkt,
    "text",
    ordnung,
    istachse_txt,
    nummerierungsprinzip_txt,
    attributeprovisorisch_txt,
    istoffiziellebezeichnung_txt,
    inaenderung_txt,
    art_txt,
    identifikator,
    beschreibung,
    gueltigereintrag,
    gem_bfs,
    los,
    lieferdatum 
FROM
    adressen.gebaeudeadressen_strassenstueck_qgis_server_client_t
;