INSERT INTO awjf_waldplan_pub_v2.waldplan_aswrtung_auswertung (
	t_basket,
	t_datasetname,
	wirtschaftswald,
	schutzwald,
	erholungswald,
	biodiversitaet,
	schutzwald_biodiversitaet,
	wald_bestockt,
	nachteilige_nutzung,
	waldstrasse,
	maschinenweg,
	bauten_anlagen,
	rodung_temporaer,
	gewaesser,
	waldreservat,
	altholzinsel,
	waldrand,
	lichter_wald,
	lebensraum_prioritaer,
	andere_foerderflaeche,
	waldflaeche_produktiv,
	waldflaeche_unproduktiv,
	wirtschaftswald_produktiv,
	wirtschaftswald_unproduktiv,
	schutzwald_produktiv,
	schutzwald_unproduktiv,
	erholungswald_produktiv,
	erholungswald_unproduktiv,
	biodiversitaet_produktiv,
	biodiversitaet_unproduktiv,
	schutzwald_bio_produktiv,
	schutzwald_bio_unproduktiv,
	waldflaeche_hiebrel,
	waldflaeche_n_hiebrel,
	wirtschaftswald_hiebrel,
	wirtschaftswald_n_hiebrel,
	schutzwald_hiebrel,
	schutzwald_n_hiebrel,
	erholungswald_hiebrel,
	erholungswald_n_hiebrel,
	biodiversitaet_hiebrel,
	biodiversitaet_n_hiebrel,
	schutzwald_bio_hiebrel,
	schutzwald_bio_n_hiebrel,
	wald_bestockt_hiebrel,
	wald_bestockt_n_hiebrel,
	nachteilige_nutzung_hiebrel,
	nachteilige_nutzung_n_hiebrel,
	wirtschaftswald_wald_bestockt,
	wirtschaftswald_nt_nutzung,
	wirtschaftswald_waldstrasse,
	wirtschaftswald_maschinenweg,
	wirtschaftswald_bauanl,
	wirtschaftswald_gewaesser,
	wirtschaftswald_rodung_temp,
	schutzwald_wald_bestockt,
	schutzwald_nt_nutzung,
	schutzwald_waldstrasse,
	schutzwald_maschinenweg,
	schutzwald_bauanl,
	schutzwald_gewaesser,
	schutzwald_rodung_temp,
	erholungswald_wald_bestockt,
	erholungswald_nt_nutzung,
	erholungswald_waldstrasse,
	erholungswald_maschinenweg,
	erholungswald_bauanl,
	erholungswald_gewaesser,
	erholungswald_rodung_temp,
	biodiversitaet_wald_bestockt,
	biodiversitaet_nt_nutzung,
	biodiversitaet_waldstrasse,
	biodiversitaet_maschinenweg,
	biodiversitaet_bauanl,
	biodiversitaet_gewaesser,
	biodiversitaet_rodung_temp,
	schutzwald_bio_wald_bestockt,
	schutzwald_bio_nt_nutzung,
	schutzwald_bio_waldstrasse,
	schutzwald_bio_maschinenweg,
	schutzwald_bio_bauanl,
	schutzwald_bio_gewaesser,
	schutzwald_bio_rodung_temp,
	egrid,
	gemeinde,
	grundbuch,
	forstkreis,
	forstkreis_txt,
	forstrevier,
	forstbetrieb,
	wirtschaftszone,
	wirtschaftszone_txt,
	grundstuecknummer,
	flaechenmass,
	eigentuemer,
	eigentuemer_txt,
	eigentuemerinformation,
	wytweide_flaeche,
	waldflaeche,
	geometrie,
	bemerkung	
)
	SELECT 
		gs.t_basket_auswertung::bigint AS t_basket,
		gs.t_datasetname,
		wfg.wirtschaftswald,
		wfg.schutzwald,
		wfg.erholungswald,
		wfg.biodiversitaet,
		wfg.schutzwald_biodiversitaet,
		wng.wald_bestockt,
		wng.nachteilige_nutzung,
		wng.waldstrasse,
		wng.maschinenweg,
		wng.bauten_anlagen,
		wng.rodung_temporaer,
		wng.gewaesser,
		biog.waldreservat,
		biog.altholzinsel,
		biog.waldrand,
		biog.lichter_wald,
		biog.lebensraum_prioritaer,
		biog.andere_foerderflaeche,
		wfprod.waldflaeche_produktiv,
		wfprod.waldflaeche_unproduktiv,
		wfprod.wirtschaftswald_produktiv,
		wfprod.wirtschaftswald_unproduktiv,
		wfprod.schutzwald_produktiv,
		wfprod.schutzwald_unproduktiv,
		wfprod.erholungswald_produktiv,
		wfprod.erholungswald_unproduktiv,
		wfprod.biodiversitaet_produktiv,
		wfprod.biodiversitaet_unproduktiv,
		wfprod.schutzwald_bio_produktiv,
		wfprod.schutzwald_bio_unproduktiv,
		wfhr.waldflaeche_hiebrel,
		wfhr.waldflaeche_n_hiebrel,
		wfhr.wirtschaftswald_hiebrel,
		wfhr.wirtschaftswald_n_hiebrel,
		wfhr.schutzwald_hiebrel,
		wfhr.schutzwald_n_hiebrel,
		wfhr.erholungswald_hiebrel,
		wfhr.erholungswald_n_hiebrel,
		wfhr.biodiversitaet_hiebrel,
		wfhr.biodiversitaet_n_hiebrel,
		wfhr.schutzwald_bio_hiebrel,
		wfhr.schutzwald_bio_n_hiebrel,
		wnhr.wald_bestockt_hiebrel,
		wnhr.wald_bestockt_n_hiebrel,
		wnhr.nachteilige_nutzung_hiebrel,
		wnhr.nachteilige_nutzung_n_hiebrel,
		wnw.wirtschaftswald_wald_bestockt,
		wnw.wirtschaftswald_nt_nutzung,
		wnw.wirtschaftswald_waldstrasse,
		wnw.wirtschaftswald_maschinenweg,
		wnw.wirtschaftswald_bauanl,
		wnw.wirtschaftswald_gewaesser,
		wnw.wirtschaftswald_rodung_temp,
		wnw.schutzwald_wald_bestockt,
		wnw.schutzwald_nt_nutzung,
		wnw.schutzwald_waldstrasse,
		wnw.schutzwald_maschinenweg,
		wnw.schutzwald_bauanl,
		wnw.schutzwald_gewaesser,
		wnw.schutzwald_rodung_temp,
		wnw.erholungswald_wald_bestockt,
		wnw.erholungswald_nt_nutzung,
		wnw.erholungswald_waldstrasse,
		wnw.erholungswald_maschinenweg,
		wnw.erholungswald_bauanl,
		wnw.erholungswald_gewaesser,
		wnw.erholungswald_rodung_temp,
		wnw.biodiversitaet_wald_bestockt,
		wnw.biodiversitaet_nt_nutzung,
		wnw.biodiversitaet_waldstrasse,
		wnw.biodiversitaet_maschinenweg,
		wnw.biodiversitaet_bauanl,
		wnw.biodiversitaet_gewaesser,
		wnw.biodiversitaet_rodung_temp,
		wnw.schutzwald_bio_wald_bestockt,
		wnw.schutzwald_bio_nt_nutzung,
		wnw.schutzwald_bio_waldstrasse,
		wnw.schutzwald_bio_maschinenweg,
		wnw.schutzwald_bio_bauanl,
		wnw.schutzwald_bio_gewaesser,
		wnw.schutzwald_bio_rodung_temp,
		gs.egrid,
		gs.gemeinde,
		gs.grundbuch,
		gs.forstkreis,
		gs.forstkreis_txt,
		gs.forstrevier,
		gs.forstbetrieb,
		gs.wirtschaftszone,
		gs.wirtschaftszone_txt,
		gs.grundstuecknummer,
		gs.flaechenmass,
		gs.eigentuemer,
		gs.eigentuemer_txt,
		gs.eigentuemerinformation,
		wyt.flaeche AS wytweide_flaeche,
		wfprod.waldflaeche,
		wfgf.geometrie,
		gs.bemerkung
	FROM
		grundstueck AS gs
	LEFT JOIN waldfunktion_nach_waldnutzung AS wnw
		ON gs.egrid = wnw.egrid 
	LEFT JOIN wytweide_grundstueck AS wyt 
		ON gs.egrid = wyt.egrid
	LEFT JOIN waldfunktionsflaechen_grundstueck AS wfg 
		ON gs.egrid = wfg.egrid
	LEFT JOIN waldnutzungsflaechen_grundstueck AS wng
		ON gs.egrid = wng.egrid
	LEFT JOIN biodiversitaetsobjekte_grundstueck AS biog
		ON gs.egrid = biog.egrid
	LEFT JOIN waldflaeche_produktiv AS wfprod 
		ON gs.egrid = wfprod.egrid
	LEFT JOIN waldfunktion_hiebsatzrelevant AS wfhr
		ON gs.egrid = wfhr.egrid
	LEFT JOIN waldnutzung_hiebsatzrelevant AS wnhr
		ON gs.egrid = wnhr.egrid
	LEFT JOIN waldflaeche_grundstueck_final AS wfgf
		ON gs.egrid = wfgf.egrid
	WHERE 
		wfgf.geometrie IS NOT NULL