pipeline {
    agent { label 'master' }
    options {
        timeout(time: 6, unit: 'HOURS')
    }
    stages {
        stage('Run job agi_av_export_ai with topic=av_jahresstand') {
            steps {
                // Special case:
                // Run a different GRETL-Job with specific parameter value,
                // instead of running the gretl command as usual
                build job: 'agi_av_export_ai', parameters: [string(name: 'topic', value: 'av_jahresstand'), string(name: 'BRANCH', value: "${params.BRANCH ?: 'main'}")]
            }
        }
    }
    post {
        unsuccessful {
            emailext (
                to: "${currentBuild.getBuildCauses()[0]._class == 'hudson.model.Cause$UserIdCause' ? emailextrecipients([requestor()]) : '$DEFAULT_RECIPIENTS'}",
                subject: "GRETL-Job ${JOB_NAME} (${BUILD_DISPLAY_NAME}) ist fehlgeschlagen",
                body: "Die Ausführung des GRETL-Jobs ${JOB_NAME} (${BUILD_DISPLAY_NAME}) war nicht erfolgreich. Details dazu finden Sie in den Log-Meldungen unter ${RUN_DISPLAY_URL}."
            )
        }
        success {
            emailext (
                to: "${currentBuild.getBuildCauses()[0]._class == 'hudson.model.Cause$UserIdCause' ? emailextrecipients([requestor()]) : '$DEFAULT_RECIPIENTS'}",
                subject: "GRETL-Job ${JOB_NAME} (${BUILD_DISPLAY_NAME}) wurde erfolgreich ausgeführt",
                body: "Zur Kenntnisnahme: Soeben wurde der GRETL-Job ${JOB_NAME} (${BUILD_DISPLAY_NAME}) erfolgreich ausgeführt. Details dazu finden Sie in den Log-Meldungen unter ${RUN_DISPLAY_URL}."
            )
        }
    }
}
