pipeline {
    agent { label env.NODE_LABEL ?: 'gretl' }
    options {
        timeout(time: 6, unit: 'HOURS')
    }
    stages {
        stage('Run GRETL job') {
            steps {
                git url: "${env.GIT_REPO_URL}", branch: "${params.BRANCH ?: 'main'}", changelog: false
                container('gretl') {
                    dir(env.JOB_BASE_NAME) {
                        // Job with file upload with keeping the original file name (file will be available in GRETL in directory $buildDir/in/)
                        script { env.UPLOAD_FILE_NAME = 'data.zip'} // File name must match the value of parameters.stashedFile in job.properties file
                        script { env.ORIGINAL_FILE_NAME = env."${env.UPLOAD_FILE_NAME}_FILENAME"} // feels somewhat hacky; works even if UPLOAD_FILE_NAME contains a dot
                        dir('build/in') {
                            unstash name: env.UPLOAD_FILE_NAME
                            sh "[ -s ${env.UPLOAD_FILE_NAME} ] && mv ${env.UPLOAD_FILE_NAME} ${env.ORIGINAL_FILE_NAME} || rm -f ${env.UPLOAD_FILE_NAME}" // Rename file to original name or remove file if it's empty (i.e. if none has been uploaded)
                        }
                        // Pass property uploadFileName which contains the original file name, so uploaded file will be accessible in GRETL at $buildDir/in/$uploadFileName)
                        sh "gretl -P uploadFileName=${env.ORIGINAL_FILE_NAME}"
                    }
                }
            }
        }
    }
    post {
        unsuccessful {
            emailext (
                // If build was started by a user ("UserIdCause"), then set to user that started the build (the "requestor");
                // otherweise set to $DEFAULT_RECIPIENTS
                // Good to know: $DEFAULT_RECIPIENTS is not a variable,
                // but rather a token which will be replaced by the Email Extension plugin
                // Docs: https://plugins.jenkins.io/email-ext/#plugin-content-tokens
                to: "${currentBuild.getBuildCauses()[0]._class == 'hudson.model.Cause$UserIdCause' ? emailextrecipients([requestor()]) : '$DEFAULT_RECIPIENTS'}",
                subject: "GRETL-Job ${JOB_NAME} (${BUILD_DISPLAY_NAME}) ist fehlgeschlagen",
                body: "Die Ausführung des GRETL-Jobs ${JOB_NAME} (${BUILD_DISPLAY_NAME}) war nicht erfolgreich. Details dazu finden Sie in den Log-Meldungen unter ${RUN_DISPLAY_URL}."
            )
        }
    }
}
